### ISSUE TITLE
Beep sometimes doesn't stop

### ISSUE THREAD

**Issue by tpimh** [minbbb/FlappyCat#1]
In some occasions (after title screen, after jump, after game over) pin 11 goes high and stays high until next sound is played. This is probably a bug in TVout library. Which version of TVout library are you using?

I'm using [the updated version by nootropicdesign](https://github.com/nootropicdesign/arduino-tvout), Arduino IDE 1.8.13 (Linux ARM64) and Arduino Uno clone. Pin 11 is connected to a piezo buzzer.

**Comment by minbbb** [comment]
I used the library from here [https://code.google.com/archive/p/arduino-tvout/downloads](https://code.google.com/archive/p/arduino-tvout/downloads). I don't remember exactly, but most likely I used [TVoutBeta1](https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/arduino-tvout/TVoutBeta1.zip)

**Comment by tpimh** [comment]
After testing with a regular speaker, it seems that it's not a bug, but a specific of the implementation of the library. Pin 11 can stay either high or low and won't produce any sound.
